# Generated by Django 5.0.3 on 2024-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('form_title', models.CharField(max_length=100)),
                ('form_html', models.JSONField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
