# Generated by Django 5.0.3 on 2024-03-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myform',
            old_name='id',
            new_name='formid',
        ),
        migrations.CreateModel(
            name='UserSchema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=100)),
                ('form_details', models.JSONField()),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schemas', to='myform.myform')),
            ],
        ),
    ]
