# Generated by Django 5.0.3 on 2024-03-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0002_rename_id_myform_formid_userschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschema',
            name='form_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
