# Generated by Django 5.0.3 on 2024-03-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0003_userschema_form_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userschema',
            old_name='from_id',
            new_name='form_id',
        ),
    ]
